### ISSUE TITLE
Naming Convention external services file

### ISSUE THREAD

**Issue by nnzJd** [teamdigitale/dati-semantic-kubernetes#13]
Adapt the naming convention for external services file on branch "dev" like external services file on branch "prod"

![image](https://user-images.githubusercontent.com/37577928/202647931-5cdfefef-58f9-402a-9bb7-cb709c3bb284.png)

![image](https://user-images.githubusercontent.com/37577928/202648020-70e3924d-62d9-4469-a0d9-fef326997800.png)

**Comment by ioggstream** [comment]
Thanks for your feedback! The prod environment works a bit differently from the others, and files reflect this difference. Specifically, in dev/ all information is in the same file.

**Comment by ioggstream** [comment]
fixed in #14
